# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &NewOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: newOrg

        # ID to load the MSP definition as
        ID: newOrgMSP

        MSPDir: ../organizations/peerOrganizations/neworg.dot-box.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('newOrgMSP.admin', 'newOrgMSP.peer', 'newOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('newOrgMSP.admin', 'newOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('newOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('newOrgMSP.peer')"
